line-length = 79
target-version="py311"
src = ["src"]

include = ["src/main_service/**.py"]
exclude = ["src/main_service/migration/**.py"]

lint.select = [
   "T20", # flake8-print
   "I", # isort
   "F", # Pyflakes
   "E", # pycodestyle
   "W", # pycodestyle
   "N", # pep8-naming
   "ASYNC", # flake8-async
]


[lint.per-file-ignores]
"src/main_service/tests/**" = ["TID252", "PLR2004", "S101"]

[lint.isort]
no-lines-before = ["local-folder"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"
