line-length = 79
target-version="py311"
src = []

include = ["src/bond_service/**.py"]
exclude = ["src/bond_service/app/adapters/postgres/migration/**.py"]

lint.select = [
   "T20", # flake8-print
   "F", # Pyflakes
   "E", # pycodestyle
   "W", # pycodestyle
   "N", # pep8-naming
   "ASYNC", # flake8-async
   "ERA", # eradicate
   "ARG", # flake8-unused-arguments
   "I", # isort
]


[lint.per-file-ignores]
"src/bond_service/tests/**" = ["TID252", "PLR2004", "S101"]
# чтобы не удалялись metadata таблиц
"src/bond_service/app/adapters/postgres/meta.py" = ["F401"]

[lint.isort]
known-first-party = ["app"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"
