line-length = 79
target-version="py311"
src = []

include = [
   "src/bond_service/**.py",
   "src/portfolio_service/**.py",
]
exclude = [
   "src/bond_service/app/adapters/postgres/migration/**.py",
   "src/portfolio_service/app/adapters/postgres/migration/**.py",
   "template/**"
]

lint.select = [
   "T20", # flake8-print
   "F", # Pyflakes
   "E", # pycodestyle
   "W", # pycodestyle
   "N", # pep8-naming
   "ASYNC", # flake8-async
   "ERA", # eradicate
   "ARG", # flake8-unused-arguments
   "I", # isort
]


[lint.isort]
known-first-party = ["app", "tests"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"
