version: '3.5'

services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_BOND_DATABASES: bond
      POSTGRES_PORTFOLIO_DATABASES: portfolio
      POSTGRES_TEST_BOND_DATABASES: reference_bond
      POSTGRES_TEST_PORTFOLIO_DATABASES: reference_portfolio
    healthcheck:
      test: pg_isready --username "postgres" --dbname "postgres"
      interval: 1s
      retries: 5
      timeout: 5s
    ports:
      - "5432:5432"
    volumes:
      - ./docker-multiple-databases.sh:/docker-entrypoint-initdb.d/docker-multiple-databases.sh:ro
    tmpfs:
      - /var/lib/postgresql/data:rw # Necessary to speed up integration tests.

volumes:
    postgres:
