"""delete portfolios column

Revision ID: f3cf351c0599
Revises: 0f9ac6f8248a
Create Date: 2024-05-02 13:35:56.616530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cf351c0599'
down_revision: Union[str, None] = '0f9ac6f8248a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Наименование облигации'))
    # ### end Alembic commands ###
