"""drop bond table

Revision ID: dc141178a84f
Revises: f3cf351c0599
Create Date: 2024-05-02 18:58:33.962950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc141178a84f'
down_revision: Union[str, None] = 'f3cf351c0599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('portfolio_bonds_bond_isin_fkey', 'portfolio_bonds', type_='foreignkey')
    op.drop_index('ix_bonds_isin', table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Наименование облигации'),
    sa.Column('isin', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Международный идентификационный код ценной бумаги'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='Дата создания записи'),
    sa.PrimaryKeyConstraint('isin', name='bonds_pkey')
    )
    op.create_index('ix_bonds_isin', 'bonds', ['isin'], unique=True)
    op.create_foreign_key('portfolio_bonds_bond_isin_fkey', 'portfolio_bonds', 'bonds', ['bond_isin'], ['isin'], ondelete='CASCADE')
    # ### end Alembic commands ###
