"""refact table

Revision ID: b0c54573a624
Revises: f0c9944f8217
Create Date: 2024-05-07 13:48:40.559768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0c54573a624'
down_revision: Union[str, None] = 'f0c9944f8217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('operations_portfolio_bond_id_fkey', 'operations', type_='foreignkey')
    op.create_table('bonds',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор'),
    sa.Column('portfolio_id', sa.UUID(), nullable=True, comment='Идентификатор портфеля'),
    sa.Column('bond_isin', sa.String(), nullable=True, comment='Идентификатор облигации'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Дата создания записи'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonds_id'), 'bonds', ['id'], unique=True)
    op.drop_index('ix_portfolio_bonds_id', table_name='portfolio_bonds')
    op.drop_index('ix_portfolios_id', table_name='portfolios')
    op.add_column('operations', sa.Column('bond_id', sa.UUID(), nullable=True, comment='Идентификатор отношения портфеля и облигации'))
    op.create_foreign_key(None, 'operations', 'bonds', ['bond_id'], ['id'], ondelete='CASCADE')
    op.drop_column('operations', 'portfolio_bond_id')

    op.drop_table('portfolio_bonds')
    op.drop_table('portfolios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.add_column('operations', sa.Column('portfolio_bond_id', sa.UUID(), autoincrement=False, nullable=True, comment='Идентификатор отношения портфеля и облигации'))
    op.drop_column('operations', 'bond_id')
    op.drop_index(op.f('ix_bonds_id'), table_name='bonds')
    op.drop_table('bonds')

    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Идентификатор'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='Дата создания записи'),
    sa.PrimaryKeyConstraint('id', name='portfolios_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_portfolios_id', 'portfolios', ['id'], unique=True)
    op.create_table('portfolio_bonds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Идентификатор'),
    sa.Column('portfolio_id', sa.UUID(), autoincrement=False, nullable=True, comment='Идентификатор портфеля'),
    sa.Column('bond_isin', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор облигации'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='Дата создания записи'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name='portfolio_bonds_portfolio_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='portfolio_bonds_pkey')
    )
    op.create_foreign_key('operations_portfolio_bond_id_fkey', 'operations', 'portfolio_bonds', ['portfolio_bond_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_portfolio_bonds_id', 'portfolio_bonds', ['id'], unique=True)
    # ### end Alembic commands ###
